### PR TITLE
Trace child

### PR DESCRIPTION
**Pull request by adsr**

### CODE REVIEW

**Comment by adsr** [comment]
Merges after #7

**Comment by Stantheman** [comment]
Finally looked at this last night! Super cool!!

There's a race condition for short-lived processes, like:

```
./phpspy -- php -r 'echo "hello\n";'
```

If php finishes fast enough, `find_addresses` will fail and exit. [This patch](https://gist.github.com/Stantheman/38997746e7a5d590098b090c174747f1) adds a waitpid that seems to let it clean up safely (and waitpid for `-p`/PIDs that aren't ours should instantly fail).

I don't know how wild we need to get with it, the practical reason I saw this was because my terminal didn't end up on a newline when it died like this 😛

**Review by Stantheman — COMMENTED** [review]
Added the main comment, using the official review thing to say that

**Comment by adsr** [comment]
Merged

**Pull request closed without merging**
